/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SendinBlueApi) {
      root.SendinBlueApi = {};
    }
    root.SendinBlueApi.GetAccountPlan = factory(root.SendinBlueApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetAccountPlan model module.
   * @module model/GetAccountPlan
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>GetAccountPlan</code>.
   * @alias module:model/GetAccountPlan
   * @class
   * @param type {module:model/GetAccountPlan.TypeEnum} Displays the plan type of the user
   * @param creditsType {module:model/GetAccountPlan.CreditsTypeEnum} This is the type of the credit, \"User Limit\" or \"Send Limit\" are two possible types of credit of a user. \"User Limit\" implies the total number of subscribers you can add to your account, and \"Send Limit\" implies the total number of emails you can send to the subscribers in your account.
   * @param credits {Number} Remaining credits of the user. This can either be \"User Limit\" or \"Send Limit\" depending on the plan.
   */
  var exports = function(type, creditsType, credits) {
    var _this = this;

    _this['type'] = type;
    _this['creditsType'] = creditsType;
    _this['credits'] = credits;
  };

  /**
   * Constructs a <code>GetAccountPlan</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAccountPlan} obj Optional instance to populate.
   * @return {module:model/GetAccountPlan} The populated <code>GetAccountPlan</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('creditsType')) {
        obj['creditsType'] = ApiClient.convertToType(data['creditsType'], 'String');
      }
      if (data.hasOwnProperty('credits')) {
        obj['credits'] = ApiClient.convertToType(data['credits'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Displays the plan type of the user
   * @member {module:model/GetAccountPlan.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * This is the type of the credit, \"User Limit\" or \"Send Limit\" are two possible types of credit of a user. \"User Limit\" implies the total number of subscribers you can add to your account, and \"Send Limit\" implies the total number of emails you can send to the subscribers in your account.
   * @member {module:model/GetAccountPlan.CreditsTypeEnum} creditsType
   */
  exports.prototype['creditsType'] = undefined;
  /**
   * Remaining credits of the user. This can either be \"User Limit\" or \"Send Limit\" depending on the plan.
   * @member {Number} credits
   */
  exports.prototype['credits'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "payAsYouGo"
     * @const
     */
    "payAsYouGo": "payAsYouGo",
    /**
     * value: "unlimited"
     * @const
     */
    "unlimited": "unlimited",
    /**
     * value: "free"
     * @const
     */
    "free": "free",
    /**
     * value: "subscription"
     * @const
     */
    "subscription": "subscription",
    /**
     * value: "sms"
     * @const
     */
    "sms": "sms",
    /**
     * value: "reseller"
     * @const
     */
    "reseller": "reseller"  };

  /**
   * Allowed values for the <code>creditsType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CreditsTypeEnum = {
    /**
     * value: "userLimit"
     * @const
     */
    "userLimit": "userLimit",
    /**
     * value: "sendLimit"
     * @const
     */
    "sendLimit": "sendLimit"  };


  return exports;
}));


