/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse20015Clicked', 'model/InlineResponse20015MessagesSent', 'model/InlineResponse20015Opened', 'model/InlineResponse20015TransacAttributes', 'model/InlineResponse20015Unsubscriptions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20015Clicked'), require('./InlineResponse20015MessagesSent'), require('./InlineResponse20015Opened'), require('./InlineResponse20015TransacAttributes'), require('./InlineResponse20015Unsubscriptions'));
  } else {
    // Browser globals (root is window)
    if (!root.SendinBlueApi) {
      root.SendinBlueApi = {};
    }
    root.SendinBlueApi.InlineResponse20015 = factory(root.SendinBlueApi.ApiClient, root.SendinBlueApi.InlineResponse20015Clicked, root.SendinBlueApi.InlineResponse20015MessagesSent, root.SendinBlueApi.InlineResponse20015Opened, root.SendinBlueApi.InlineResponse20015TransacAttributes, root.SendinBlueApi.InlineResponse20015Unsubscriptions);
  }
}(this, function(ApiClient, InlineResponse20015Clicked, InlineResponse20015MessagesSent, InlineResponse20015Opened, InlineResponse20015TransacAttributes, InlineResponse20015Unsubscriptions) {
  'use strict';




  /**
   * The InlineResponse20015 model module.
   * @module model/InlineResponse20015
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>InlineResponse20015</code>.
   * Campaign Statistics for the contact
   * @alias module:model/InlineResponse20015
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>InlineResponse20015</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20015} obj Optional instance to populate.
   * @return {module:model/InlineResponse20015} The populated <code>InlineResponse20015</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('messagesSent')) {
        obj['messagesSent'] = ApiClient.convertToType(data['messagesSent'], [InlineResponse20015MessagesSent]);
      }
      if (data.hasOwnProperty('hardBounces')) {
        obj['hardBounces'] = ApiClient.convertToType(data['hardBounces'], [InlineResponse20015MessagesSent]);
      }
      if (data.hasOwnProperty('softBounces')) {
        obj['softBounces'] = ApiClient.convertToType(data['softBounces'], [InlineResponse20015MessagesSent]);
      }
      if (data.hasOwnProperty('complaints')) {
        obj['complaints'] = ApiClient.convertToType(data['complaints'], [InlineResponse20015MessagesSent]);
      }
      if (data.hasOwnProperty('unsubscriptions')) {
        obj['unsubscriptions'] = InlineResponse20015Unsubscriptions.constructFromObject(data['unsubscriptions']);
      }
      if (data.hasOwnProperty('opened')) {
        obj['opened'] = ApiClient.convertToType(data['opened'], [InlineResponse20015Opened]);
      }
      if (data.hasOwnProperty('clicked')) {
        obj['clicked'] = ApiClient.convertToType(data['clicked'], [InlineResponse20015Clicked]);
      }
      if (data.hasOwnProperty('transacAttributes')) {
        obj['transacAttributes'] = ApiClient.convertToType(data['transacAttributes'], [InlineResponse20015TransacAttributes]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/InlineResponse20015MessagesSent>} messagesSent
   */
  exports.prototype['messagesSent'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20015MessagesSent>} hardBounces
   */
  exports.prototype['hardBounces'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20015MessagesSent>} softBounces
   */
  exports.prototype['softBounces'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20015MessagesSent>} complaints
   */
  exports.prototype['complaints'] = undefined;
  /**
   * @member {module:model/InlineResponse20015Unsubscriptions} unsubscriptions
   */
  exports.prototype['unsubscriptions'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20015Opened>} opened
   */
  exports.prototype['opened'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20015Clicked>} clicked
   */
  exports.prototype['clicked'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20015TransacAttributes>} transacAttributes
   */
  exports.prototype['transacAttributes'] = undefined;



  return exports;
}));


