/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2008StatisticsCampaignStats', 'model/InlineResponse2008StatisticsLinksStats'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2008StatisticsCampaignStats'), require('./InlineResponse2008StatisticsLinksStats'));
  } else {
    // Browser globals (root is window)
    if (!root.SendinBlueApi) {
      root.SendinBlueApi = {};
    }
    root.SendinBlueApi.InlineResponse2008Statistics = factory(root.SendinBlueApi.ApiClient, root.SendinBlueApi.InlineResponse2008StatisticsCampaignStats, root.SendinBlueApi.InlineResponse2008StatisticsLinksStats);
  }
}(this, function(ApiClient, InlineResponse2008StatisticsCampaignStats, InlineResponse2008StatisticsLinksStats) {
  'use strict';




  /**
   * The InlineResponse2008Statistics model module.
   * @module model/InlineResponse2008Statistics
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>InlineResponse2008Statistics</code>.
   * @alias module:model/InlineResponse2008Statistics
   * @class
   * @param campaignStats {Array.<module:model/InlineResponse2008StatisticsCampaignStats>} 
   * @param mirrorClick {Number} Number of clicks on mirror link
   * @param remaining {Number} Number of remaning emails to send
   * @param linksStats {Object.<String, module:model/InlineResponse2008StatisticsLinksStats>} 
   * @param statsByDomain {Object.<String, module:model/InlineResponse2008StatisticsCampaignStats>} 
   */
  var exports = function(campaignStats, mirrorClick, remaining, linksStats, statsByDomain) {
    var _this = this;

    _this['campaignStats'] = campaignStats;
    _this['mirrorClick'] = mirrorClick;
    _this['remaining'] = remaining;
    _this['linksStats'] = linksStats;
    _this['statsByDomain'] = statsByDomain;
  };

  /**
   * Constructs a <code>InlineResponse2008Statistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2008Statistics} obj Optional instance to populate.
   * @return {module:model/InlineResponse2008Statistics} The populated <code>InlineResponse2008Statistics</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('campaignStats')) {
        obj['campaignStats'] = ApiClient.convertToType(data['campaignStats'], [InlineResponse2008StatisticsCampaignStats]);
      }
      if (data.hasOwnProperty('mirrorClick')) {
        obj['mirrorClick'] = ApiClient.convertToType(data['mirrorClick'], 'Number');
      }
      if (data.hasOwnProperty('remaining')) {
        obj['remaining'] = ApiClient.convertToType(data['remaining'], 'Number');
      }
      if (data.hasOwnProperty('linksStats')) {
        obj['linksStats'] = ApiClient.convertToType(data['linksStats'], {'String': InlineResponse2008StatisticsLinksStats});
      }
      if (data.hasOwnProperty('statsByDomain')) {
        obj['statsByDomain'] = ApiClient.convertToType(data['statsByDomain'], {'String': InlineResponse2008StatisticsCampaignStats});
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/InlineResponse2008StatisticsCampaignStats>} campaignStats
   */
  exports.prototype['campaignStats'] = undefined;
  /**
   * Number of clicks on mirror link
   * @member {Number} mirrorClick
   */
  exports.prototype['mirrorClick'] = undefined;
  /**
   * Number of remaning emails to send
   * @member {Number} remaining
   */
  exports.prototype['remaining'] = undefined;
  /**
   * @member {Object.<String, module:model/InlineResponse2008StatisticsLinksStats>} linksStats
   */
  exports.prototype['linksStats'] = undefined;
  /**
   * @member {Object.<String, module:model/InlineResponse2008StatisticsCampaignStats>} statsByDomain
   */
  exports.prototype['statsByDomain'] = undefined;



  return exports;
}));


