/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse200Address', 'model/InlineResponse200MarketingAutomation', 'model/InlineResponse200Plan', 'model/InlineResponse200Relay'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse200Address'), require('./InlineResponse200MarketingAutomation'), require('./InlineResponse200Plan'), require('./InlineResponse200Relay'));
  } else {
    // Browser globals (root is window)
    if (!root.SendinBlueApi) {
      root.SendinBlueApi = {};
    }
    root.SendinBlueApi.InlineResponse200 = factory(root.SendinBlueApi.ApiClient, root.SendinBlueApi.InlineResponse200Address, root.SendinBlueApi.InlineResponse200MarketingAutomation, root.SendinBlueApi.InlineResponse200Plan, root.SendinBlueApi.InlineResponse200Relay);
  }
}(this, function(ApiClient, InlineResponse200Address, InlineResponse200MarketingAutomation, InlineResponse200Plan, InlineResponse200Relay) {
  'use strict';




  /**
   * The InlineResponse200 model module.
   * @module model/InlineResponse200
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>InlineResponse200</code>.
   * @alias module:model/InlineResponse200
   * @class
   * @param email {String} Login Email
   * @param firstName {String} First Name
   * @param lastName {String} Last Name
   * @param companyName {String} Name of the company
   * @param plan {Array.<module:model/InlineResponse200Plan>} Information about your plans and credits
   */
  var exports = function(email, firstName, lastName, companyName, plan) {
    var _this = this;

    _this['email'] = email;
    _this['firstName'] = firstName;
    _this['lastName'] = lastName;
    _this['companyName'] = companyName;

    _this['plan'] = plan;


  };

  /**
   * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200} obj Optional instance to populate.
   * @return {module:model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('firstName')) {
        obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
      }
      if (data.hasOwnProperty('lastName')) {
        obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
      }
      if (data.hasOwnProperty('companyName')) {
        obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = InlineResponse200Address.constructFromObject(data['address']);
      }
      if (data.hasOwnProperty('plan')) {
        obj['plan'] = ApiClient.convertToType(data['plan'], [InlineResponse200Plan]);
      }
      if (data.hasOwnProperty('relay')) {
        obj['relay'] = InlineResponse200Relay.constructFromObject(data['relay']);
      }
      if (data.hasOwnProperty('marketingAutomation')) {
        obj['marketingAutomation'] = InlineResponse200MarketingAutomation.constructFromObject(data['marketingAutomation']);
      }
    }
    return obj;
  }

  /**
   * Login Email
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * First Name
   * @member {String} firstName
   */
  exports.prototype['firstName'] = undefined;
  /**
   * Last Name
   * @member {String} lastName
   */
  exports.prototype['lastName'] = undefined;
  /**
   * Name of the company
   * @member {String} companyName
   */
  exports.prototype['companyName'] = undefined;
  /**
   * @member {module:model/InlineResponse200Address} address
   */
  exports.prototype['address'] = undefined;
  /**
   * Information about your plans and credits
   * @member {Array.<module:model/InlineResponse200Plan>} plan
   */
  exports.prototype['plan'] = undefined;
  /**
   * @member {module:model/InlineResponse200Relay} relay
   */
  exports.prototype['relay'] = undefined;
  /**
   * @member {module:model/InlineResponse200MarketingAutomation} marketingAutomation
   */
  exports.prototype['marketingAutomation'] = undefined;



  return exports;
}));


