/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.26
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SibApiV3Sdk);
  }
}(this, function(expect, SibApiV3Sdk) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateDoiContact', function() {
      beforeEach(function() {
        instance = new SibApiV3Sdk.CreateDoiContact();
      });

      it('should create an instance of CreateDoiContact', function() {
        // TODO: update the code to test CreateDoiContact
        expect(instance).to.be.a(SibApiV3Sdk.CreateDoiContact);
      });

      it('should have the property email (base name: "email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property attributes (base name: "attributes")', function() {
        // TODO: update the code to test the property attributes
        expect(instance).to.have.property('attributes');
        // expect(instance.attributes).to.be(expectedValueLiteral);
      });

      it('should have the property includeListIds (base name: "includeListIds")', function() {
        // TODO: update the code to test the property includeListIds
        expect(instance).to.have.property('includeListIds');
        // expect(instance.includeListIds).to.be(expectedValueLiteral);
      });

      it('should have the property excludeListIds (base name: "excludeListIds")', function() {
        // TODO: update the code to test the property excludeListIds
        expect(instance).to.have.property('excludeListIds');
        // expect(instance.excludeListIds).to.be(expectedValueLiteral);
      });

      it('should have the property templateId (base name: "templateId")', function() {
        // TODO: update the code to test the property templateId
        expect(instance).to.have.property('templateId');
        // expect(instance.templateId).to.be(expectedValueLiteral);
      });

      it('should have the property redirectionUrl (base name: "redirectionUrl")', function() {
        // TODO: update the code to test the property redirectionUrl
        expect(instance).to.have.property('redirectionUrl');
        // expect(instance.redirectionUrl).to.be(expectedValueLiteral);
      });

    });
  });

}));
