/**
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SibApiV3Sdk);
  }
}(this, function(expect, SibApiV3Sdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SibApiV3Sdk.GetCampaignOverview();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetCampaignOverview', function() {
    it('should create an instance of GetCampaignOverview', function() {
      // uncomment below and update the code to test GetCampaignOverview
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be.a(SibApiV3Sdk.GetCampaignOverview);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property scheduledAt (base name: "scheduledAt")', function() {
      // uncomment below and update the code to test the property scheduledAt
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property abTesting (base name: "abTesting")', function() {
      // uncomment below and update the code to test the property abTesting
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property subjectA (base name: "subjectA")', function() {
      // uncomment below and update the code to test the property subjectA
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property subjectB (base name: "subjectB")', function() {
      // uncomment below and update the code to test the property subjectB
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property splitRule (base name: "splitRule")', function() {
      // uncomment below and update the code to test the property splitRule
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property winnerCriteria (base name: "winnerCriteria")', function() {
      // uncomment below and update the code to test the property winnerCriteria
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property winnerDelay (base name: "winnerDelay")', function() {
      // uncomment below and update the code to test the property winnerDelay
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

    it('should have the property sendAtBestTime (base name: "sendAtBestTime")', function() {
      // uncomment below and update the code to test the property sendAtBestTime
      //var instane = new SibApiV3Sdk.GetCampaignOverview();
      //expect(instance).to.be();
    });

  });

}));
