/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.26
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SibApiV3Sdk);
  }
}(this, function(expect, SibApiV3Sdk) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RequestContactImport', function() {
      beforeEach(function() {
        instance = new SibApiV3Sdk.RequestContactImport();
      });

      it('should create an instance of RequestContactImport', function() {
        // TODO: update the code to test RequestContactImport
        expect(instance).to.be.a(SibApiV3Sdk.RequestContactImport);
      });

      it('should have the property fileUrl (base name: "fileUrl")', function() {
        // TODO: update the code to test the property fileUrl
        expect(instance).to.have.property('fileUrl');
        // expect(instance.fileUrl).to.be(expectedValueLiteral);
      });

      it('should have the property fileBody (base name: "fileBody")', function() {
        // TODO: update the code to test the property fileBody
        expect(instance).to.have.property('fileBody');
        // expect(instance.fileBody).to.be(expectedValueLiteral);
      });

      it('should have the property jsonBody (base name: "jsonBody")', function() {
        // TODO: update the code to test the property jsonBody
        expect(instance).to.have.property('jsonBody');
        // expect(instance.jsonBody).to.be(expectedValueLiteral);
      });

      it('should have the property listIds (base name: "listIds")', function() {
        // TODO: update the code to test the property listIds
        expect(instance).to.have.property('listIds');
        // expect(instance.listIds).to.be(expectedValueLiteral);
      });

      it('should have the property notifyUrl (base name: "notifyUrl")', function() {
        // TODO: update the code to test the property notifyUrl
        expect(instance).to.have.property('notifyUrl');
        // expect(instance.notifyUrl).to.be(expectedValueLiteral);
      });

      it('should have the property newList (base name: "newList")', function() {
        // TODO: update the code to test the property newList
        expect(instance).to.have.property('newList');
        // expect(instance.newList).to.be(expectedValueLiteral);
      });

      it('should have the property emailBlacklist (base name: "emailBlacklist")', function() {
        // TODO: update the code to test the property emailBlacklist
        expect(instance).to.have.property('emailBlacklist');
        // expect(instance.emailBlacklist).to.be(expectedValueLiteral);
      });

      it('should have the property smsBlacklist (base name: "smsBlacklist")', function() {
        // TODO: update the code to test the property smsBlacklist
        expect(instance).to.have.property('smsBlacklist');
        // expect(instance.smsBlacklist).to.be(expectedValueLiteral);
      });

      it('should have the property updateExistingContacts (base name: "updateExistingContacts")', function() {
        // TODO: update the code to test the property updateExistingContacts
        expect(instance).to.have.property('updateExistingContacts');
        // expect(instance.updateExistingContacts).to.be(expectedValueLiteral);
      });

      it('should have the property emptyContactsAttributes (base name: "emptyContactsAttributes")', function() {
        // TODO: update the code to test the property emptyContactsAttributes
        expect(instance).to.have.property('emptyContactsAttributes');
        // expect(instance.emptyContactsAttributes).to.be(expectedValueLiteral);
      });

    });
  });

}));
