/*
 * SendinBlue API
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.26
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SibApiV3Sdk);
  }
}(this, function(expect, SibApiV3Sdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SibApiV3Sdk.ConversationsApi();
  });

  describe('(package)', function() {
    describe('ConversationsApi', function() {
      describe('conversationsAgentOnlinePingPost', function() {
        it('should call conversationsAgentOnlinePingPost successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsAgentOnlinePingPost call
          /*
          var body = new SibApiV3Sdk.Body12();
          body.agentId = "d9nKoegKSjmCtyK78";
          body.receivedFrom = "SuperAwesomeHelpdesk";
          body.agentEmail = "liz@getwear.com";
          body.agentName = "Liz";

          instance.conversationsAgentOnlinePingPost(body).then(function(data) {

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('conversationsMessagesIdDelete', function() {
        it('should call conversationsMessagesIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsMessagesIdDelete call
          /*
          var id = "id_example";

          instance.conversationsMessagesIdDelete(id).then(function(data) {

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('conversationsMessagesIdGet', function() {
        it('should call conversationsMessagesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsMessagesIdGet call and complete the assertions
          /*
          var id = "id_example";

          instance.conversationsMessagesIdGet(id).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SibApiV3Sdk.ConversationsMessage);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("eYBEm3gq3zc5ayE2g");
            expect(data.type).to.be.a('string');
            expect(data.type).to.be("agent");
            expect(data.text).to.be.a('string');
            expect(data.text).to.be("Good morning! How can I help you?");
            expect(data.visitorId).to.be.a('string');
            expect(data.visitorId).to.be("kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg");
            expect(data.agentId).to.be.a('string');
            expect(data.agentId).to.be("d9nKoegKSjmCtyK78");
            expect(data.agentName).to.be.a('string');
            expect(data.agentName).to.be("Liz");
            expect(data.createdAt).to.be.a('number');
            expect(data.createdAt).to.be(1470222622433);
            expect(data.isPushed).to.be.a('boolean');
            expect(data.isPushed).to.be(true);
            expect(data.receivedFrom).to.be.a('string');
            expect(data.receivedFrom).to.be("SuperAwesomeHelpdesk");
            expect(data.file).to.be.a(SibApiV3Sdk.ConversationsMessageFile);
                  expect(data.file.filename).to.be.a('string');
              expect(data.file.filename).to.be("conversations.png");
              expect(data.file.size).to.be.a('number');
              expect(data.file.size).to.be(15538);
              expect(data.file.isImage).to.be.a('boolean');
              expect(data.file.isImage).to.be(true);
              expect(data.file.url).to.be.a('string');
              expect(data.file.url).to.be("https://ucarecdn.com/cee5c10c-8302-45c1-b1fb-43860ca941a9/");
              expect(data.file.imageInfo).to.be.a(SibApiV3Sdk.ConversationsMessageFileImageInfo);
                    expect(data.file.imageInfo.width).to.be.a('number');
                expect(data.file.imageInfo.width).to.be(1129);
                expect(data.file.imageInfo.height).to.be.a('number');
                expect(data.file.imageInfo.height).to.be(525);
                expect(data.file.imageInfo.previewUrl).to.be.a('string');
                expect(data.file.imageInfo.previewUrl).to.be("https://ucarecdn.com/03cd56cd-1de9-4f65-996d-08afdf27fa1b/-/preview/800x800/-/quality/lighter/");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('conversationsMessagesIdPut', function() {
        it('should call conversationsMessagesIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsMessagesIdPut call and complete the assertions
          /*
          var id = "id_example";
          var opts = {};
          opts.body = new SibApiV3Sdk.Body9();
          opts.body.text = "";

          instance.conversationsMessagesIdPut(id, opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SibApiV3Sdk.ConversationsMessage);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("eYBEm3gq3zc5ayE2g");
            expect(data.type).to.be.a('string');
            expect(data.type).to.be("agent");
            expect(data.text).to.be.a('string');
            expect(data.text).to.be("Good morning! How can I help you?");
            expect(data.visitorId).to.be.a('string');
            expect(data.visitorId).to.be("kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg");
            expect(data.agentId).to.be.a('string');
            expect(data.agentId).to.be("d9nKoegKSjmCtyK78");
            expect(data.agentName).to.be.a('string');
            expect(data.agentName).to.be("Liz");
            expect(data.createdAt).to.be.a('number');
            expect(data.createdAt).to.be(1470222622433);
            expect(data.isPushed).to.be.a('boolean');
            expect(data.isPushed).to.be(true);
            expect(data.receivedFrom).to.be.a('string');
            expect(data.receivedFrom).to.be("SuperAwesomeHelpdesk");
            expect(data.file).to.be.a(SibApiV3Sdk.ConversationsMessageFile);
                  expect(data.file.filename).to.be.a('string');
              expect(data.file.filename).to.be("conversations.png");
              expect(data.file.size).to.be.a('number');
              expect(data.file.size).to.be(15538);
              expect(data.file.isImage).to.be.a('boolean');
              expect(data.file.isImage).to.be(true);
              expect(data.file.url).to.be.a('string');
              expect(data.file.url).to.be("https://ucarecdn.com/cee5c10c-8302-45c1-b1fb-43860ca941a9/");
              expect(data.file.imageInfo).to.be.a(SibApiV3Sdk.ConversationsMessageFileImageInfo);
                    expect(data.file.imageInfo.width).to.be.a('number');
                expect(data.file.imageInfo.width).to.be(1129);
                expect(data.file.imageInfo.height).to.be.a('number');
                expect(data.file.imageInfo.height).to.be(525);
                expect(data.file.imageInfo.previewUrl).to.be.a('string');
                expect(data.file.imageInfo.previewUrl).to.be("https://ucarecdn.com/03cd56cd-1de9-4f65-996d-08afdf27fa1b/-/preview/800x800/-/quality/lighter/");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('conversationsMessagesPost', function() {
        it('should call conversationsMessagesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsMessagesPost call and complete the assertions
          /*
          var body = new SibApiV3Sdk.Body8();
          body.visitorId = "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg";
          body.text = "Hello! How can I help you?";
          body.agentId = "d9nKoegKSjmCtyK78";
          body.receivedFrom = "SuperAwesomeHelpdesk";
          body.agentEmail = "liz@getwear.com";
          body.agentName = "Liz";

          instance.conversationsMessagesPost(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SibApiV3Sdk.ConversationsMessage);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("eYBEm3gq3zc5ayE2g");
            expect(data.type).to.be.a('string');
            expect(data.type).to.be("agent");
            expect(data.text).to.be.a('string');
            expect(data.text).to.be("Good morning! How can I help you?");
            expect(data.visitorId).to.be.a('string');
            expect(data.visitorId).to.be("kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg");
            expect(data.agentId).to.be.a('string');
            expect(data.agentId).to.be("d9nKoegKSjmCtyK78");
            expect(data.agentName).to.be.a('string');
            expect(data.agentName).to.be("Liz");
            expect(data.createdAt).to.be.a('number');
            expect(data.createdAt).to.be(1470222622433);
            expect(data.isPushed).to.be.a('boolean');
            expect(data.isPushed).to.be(true);
            expect(data.receivedFrom).to.be.a('string');
            expect(data.receivedFrom).to.be("SuperAwesomeHelpdesk");
            expect(data.file).to.be.a(SibApiV3Sdk.ConversationsMessageFile);
                  expect(data.file.filename).to.be.a('string');
              expect(data.file.filename).to.be("conversations.png");
              expect(data.file.size).to.be.a('number');
              expect(data.file.size).to.be(15538);
              expect(data.file.isImage).to.be.a('boolean');
              expect(data.file.isImage).to.be(true);
              expect(data.file.url).to.be.a('string');
              expect(data.file.url).to.be("https://ucarecdn.com/cee5c10c-8302-45c1-b1fb-43860ca941a9/");
              expect(data.file.imageInfo).to.be.a(SibApiV3Sdk.ConversationsMessageFileImageInfo);
                    expect(data.file.imageInfo.width).to.be.a('number');
                expect(data.file.imageInfo.width).to.be(1129);
                expect(data.file.imageInfo.height).to.be.a('number');
                expect(data.file.imageInfo.height).to.be(525);
                expect(data.file.imageInfo.previewUrl).to.be.a('string');
                expect(data.file.imageInfo.previewUrl).to.be("https://ucarecdn.com/03cd56cd-1de9-4f65-996d-08afdf27fa1b/-/preview/800x800/-/quality/lighter/");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('conversationsPushedMessagesIdDelete', function() {
        it('should call conversationsPushedMessagesIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsPushedMessagesIdDelete call
          /*
          var id = "id_example";

          instance.conversationsPushedMessagesIdDelete(id).then(function(data) {

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('conversationsPushedMessagesIdGet', function() {
        it('should call conversationsPushedMessagesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsPushedMessagesIdGet call and complete the assertions
          /*
          var id = "id_example";

          instance.conversationsPushedMessagesIdGet(id).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SibApiV3Sdk.ConversationsMessage);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("eYBEm3gq3zc5ayE2g");
            expect(data.type).to.be.a('string');
            expect(data.type).to.be("agent");
            expect(data.text).to.be.a('string');
            expect(data.text).to.be("Good morning! How can I help you?");
            expect(data.visitorId).to.be.a('string');
            expect(data.visitorId).to.be("kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg");
            expect(data.agentId).to.be.a('string');
            expect(data.agentId).to.be("d9nKoegKSjmCtyK78");
            expect(data.agentName).to.be.a('string');
            expect(data.agentName).to.be("Liz");
            expect(data.createdAt).to.be.a('number');
            expect(data.createdAt).to.be(1470222622433);
            expect(data.isPushed).to.be.a('boolean');
            expect(data.isPushed).to.be(true);
            expect(data.receivedFrom).to.be.a('string');
            expect(data.receivedFrom).to.be("SuperAwesomeHelpdesk");
            expect(data.file).to.be.a(SibApiV3Sdk.ConversationsMessageFile);
                  expect(data.file.filename).to.be.a('string');
              expect(data.file.filename).to.be("conversations.png");
              expect(data.file.size).to.be.a('number');
              expect(data.file.size).to.be(15538);
              expect(data.file.isImage).to.be.a('boolean');
              expect(data.file.isImage).to.be(true);
              expect(data.file.url).to.be.a('string');
              expect(data.file.url).to.be("https://ucarecdn.com/cee5c10c-8302-45c1-b1fb-43860ca941a9/");
              expect(data.file.imageInfo).to.be.a(SibApiV3Sdk.ConversationsMessageFileImageInfo);
                    expect(data.file.imageInfo.width).to.be.a('number');
                expect(data.file.imageInfo.width).to.be(1129);
                expect(data.file.imageInfo.height).to.be.a('number');
                expect(data.file.imageInfo.height).to.be(525);
                expect(data.file.imageInfo.previewUrl).to.be.a('string');
                expect(data.file.imageInfo.previewUrl).to.be("https://ucarecdn.com/03cd56cd-1de9-4f65-996d-08afdf27fa1b/-/preview/800x800/-/quality/lighter/");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('conversationsPushedMessagesIdPut', function() {
        it('should call conversationsPushedMessagesIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsPushedMessagesIdPut call and complete the assertions
          /*
          var id = "id_example";
          var body = new SibApiV3Sdk.Body11();
          body.text = "Your order has shipped! Here’s your tracking number: 9114 5847 4668 7775 9233 54";

          instance.conversationsPushedMessagesIdPut(id, body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SibApiV3Sdk.ConversationsMessage);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("eYBEm3gq3zc5ayE2g");
            expect(data.type).to.be.a('string');
            expect(data.type).to.be("agent");
            expect(data.text).to.be.a('string');
            expect(data.text).to.be("Good morning! How can I help you?");
            expect(data.visitorId).to.be.a('string');
            expect(data.visitorId).to.be("kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg");
            expect(data.agentId).to.be.a('string');
            expect(data.agentId).to.be("d9nKoegKSjmCtyK78");
            expect(data.agentName).to.be.a('string');
            expect(data.agentName).to.be("Liz");
            expect(data.createdAt).to.be.a('number');
            expect(data.createdAt).to.be(1470222622433);
            expect(data.isPushed).to.be.a('boolean');
            expect(data.isPushed).to.be(true);
            expect(data.receivedFrom).to.be.a('string');
            expect(data.receivedFrom).to.be("SuperAwesomeHelpdesk");
            expect(data.file).to.be.a(SibApiV3Sdk.ConversationsMessageFile);
                  expect(data.file.filename).to.be.a('string');
              expect(data.file.filename).to.be("conversations.png");
              expect(data.file.size).to.be.a('number');
              expect(data.file.size).to.be(15538);
              expect(data.file.isImage).to.be.a('boolean');
              expect(data.file.isImage).to.be(true);
              expect(data.file.url).to.be.a('string');
              expect(data.file.url).to.be("https://ucarecdn.com/cee5c10c-8302-45c1-b1fb-43860ca941a9/");
              expect(data.file.imageInfo).to.be.a(SibApiV3Sdk.ConversationsMessageFileImageInfo);
                    expect(data.file.imageInfo.width).to.be.a('number');
                expect(data.file.imageInfo.width).to.be(1129);
                expect(data.file.imageInfo.height).to.be.a('number');
                expect(data.file.imageInfo.height).to.be(525);
                expect(data.file.imageInfo.previewUrl).to.be.a('string');
                expect(data.file.imageInfo.previewUrl).to.be("https://ucarecdn.com/03cd56cd-1de9-4f65-996d-08afdf27fa1b/-/preview/800x800/-/quality/lighter/");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('conversationsPushedMessagesPost', function() {
        it('should call conversationsPushedMessagesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for conversationsPushedMessagesPost call and complete the assertions
          /*
          var body = new SibApiV3Sdk.Body10();
          body.visitorId = "kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg";
          body.text = "Your order has shipped! Here’s your tracking number: 9114 5847 3325 9667 4328 88";
          body.agentId = "PjRBMhWGen6aRHjif";
          body.groupId = "PjRBMhWGen6aRHjif";

          instance.conversationsPushedMessagesPost(body).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(SibApiV3Sdk.ConversationsMessage);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("eYBEm3gq3zc5ayE2g");
            expect(data.type).to.be.a('string');
            expect(data.type).to.be("agent");
            expect(data.text).to.be.a('string');
            expect(data.text).to.be("Good morning! How can I help you?");
            expect(data.visitorId).to.be.a('string');
            expect(data.visitorId).to.be("kZMvWhf8npAu3H6qd57w2Hv6nh6rnxvg");
            expect(data.agentId).to.be.a('string');
            expect(data.agentId).to.be("d9nKoegKSjmCtyK78");
            expect(data.agentName).to.be.a('string');
            expect(data.agentName).to.be("Liz");
            expect(data.createdAt).to.be.a('number');
            expect(data.createdAt).to.be(1470222622433);
            expect(data.isPushed).to.be.a('boolean');
            expect(data.isPushed).to.be(true);
            expect(data.receivedFrom).to.be.a('string');
            expect(data.receivedFrom).to.be("SuperAwesomeHelpdesk");
            expect(data.file).to.be.a(SibApiV3Sdk.ConversationsMessageFile);
                  expect(data.file.filename).to.be.a('string');
              expect(data.file.filename).to.be("conversations.png");
              expect(data.file.size).to.be.a('number');
              expect(data.file.size).to.be(15538);
              expect(data.file.isImage).to.be.a('boolean');
              expect(data.file.isImage).to.be(true);
              expect(data.file.url).to.be.a('string');
              expect(data.file.url).to.be("https://ucarecdn.com/cee5c10c-8302-45c1-b1fb-43860ca941a9/");
              expect(data.file.imageInfo).to.be.a(SibApiV3Sdk.ConversationsMessageFileImageInfo);
                    expect(data.file.imageInfo.width).to.be.a('number');
                expect(data.file.imageInfo.width).to.be(1129);
                expect(data.file.imageInfo.height).to.be.a('number');
                expect(data.file.imageInfo.height).to.be(525);
                expect(data.file.imageInfo.previewUrl).to.be.a('string');
                expect(data.file.imageInfo.previewUrl).to.be("https://ucarecdn.com/03cd56cd-1de9-4f65-996d-08afdf27fa1b/-/preview/800x800/-/quality/lighter/");

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
